hello: ENC[AES256_GCM,data:qlyaxq4GdwdQ/+DF7KOUPjnytcpjNPK2GSoAaNc95jwOr2BBDoZTJavKHOh2qw==,iv:uWohwAS+6sDcCSu7jHd1A2t5btqYUkF1RTuv3+NMk3s=,tag:oLUCTM0kBBEGQjdVOeyUvw==,type:str]
example_key: ENC[AES256_GCM,data:5od5mpuFGFScdyVnww==,iv:4rJyeBFr+0zi3wqaMuIaBowRyvy0TwAMP9xYEh0TD4A=,tag:eseW+tQtGSkssgESRLmBWg==,type:str]
#ENC[AES256_GCM,data:PmfvXNGyl9B06UVRcRfe3Q==,iv:psTbJ6oFqNK5uafVNX7jgSQ0lS4UgOj16byynSs+M4E=,tag:8euObyZm5lE2SK+SZDd2aQ==,type:comment]
example_array:
    - ENC[AES256_GCM,data:OFQuq4fPU+9Xh6bpemg=,iv:QQjqeQrT/goSiZaYo+Ci7e9B73quzh2eUdP5PGrayfE=,tag:jj+NuuDxQeEzj1a0U+YqRg==,type:str]
    - ENC[AES256_GCM,data:7ChjQD0RqSw08DCU1eg=,iv:4bZ9vTxXNKhpVN1yYPqG2oButG7813owL2XBrwgH16k=,tag:Wrmj2IfHpS0cIVJefGtRSw==,type:str]
example_number: ENC[AES256_GCM,data:RhdOf1Z78tLocA==,iv:XvCv87BrxujT85w47hZiSQNl8uSm18t5UclX5WnpPfw=,tag:uJFlDm/U+Wcpwbq5WGccuw==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:bdP0OA==,iv:tZX7UF+wMSg1SpOIUPo5AUSXRTF63E32pandfwldwhI=,tag:chiNfbYCrMEArbko6dVldg==,type:bool]
    - ENC[AES256_GCM,data:36TXrq4=,iv:qA8UebV4XLpL6eX97lCShOVwvKkM/mHLprSBZl1k/UY=,tag:B3sw4LJc6hR+zTZl2E4EWA==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xkw93yth563ec85syewjr39t63q4z9z68826q3xax53dkxln2snq7lpctf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbDR2VHh3S3FPM2xSdHQy
            cFQxZXZ6S1ZSc09sYjVkK1grTlFoRG05LzBNCnQ5RytYWUtRNEdBYmtZOVdjeWYz
            KzZhdjdZR0NLUXlnR25kNVAzUGpKRlUKLS0tIFZySEI3eFU0ZlFyNmxsNEJ6cytL
            SUxMMUtiemhiTVUyT2NWKzV5eHRkMTAKnlbJZPlm7Mxfw3zPTT8aUXwSqBMaGCRk
            Q4lN10HFGWEJPjyweE405FLJ+Ao4mUIOj+lZNNFmbtDkFz4drsI+Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-22T18:06:55Z"
    mac: ENC[AES256_GCM,data:IxZLouvP2e9ufCKj9WdYPM23wQho41sfeFAZc69bV17Y4kS9dOJKWOydTH8GyFuzty0GEj+5tSwUDx85PNeLcBTsG677OA7A/kdv1QFfmT87E/LnAx8iaS1CHMUZPeINDbPq4oqDQZ6sCNumXOB+oJkE4wvaDi4D2TpxtIU5LuA=,iv:VRZVjXOzjV0NnrG4gl1BbX8aiP3cTiqoxd/ZmdJAfS4=,tag:9nQi5qfqM+ZbivFiAvQYJA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
