---
keys:
  - &host "age1yfk90ks9fel80w5jx0qc27d52nrthrdfuax9yxjwvkycp9tthemsrmalgd"
  - &user "12DE37B3B4B43E3EFB0E52B22EDB840CCC5FB5E0"
creation_rules:
  - path_regex: lib/secrets/system-secrets(\.enc)?\.ya?ml$
    key_groups:
      - age:
          - *host
  - path_regex: lib/secrets/home-secrets(\.enc)?\.ya?ml$
    key_groups:
      - pgp:
          - *user
