[metadata]
description = "Search niri option"
name = "niri"

[preview]
command = "nix-search-tv preview --indexes niri '{}'"

[source]
command = "nix-search-tv print --indexes niri"

[keybindings]
ctrl-h = "actions:homepage"
ctrl-s = "actions:source"
ctrl-g = "actions:searchgithub"
enter = "actions:searchgithub"

[actions.homepage]
description = "Open homepage"
command = "nix-search-tv homepage --indexes niri '{}' | xargs -I {} bash -c '[[ \"{}\" != *\"https\" ]] && xdg-open \"{}\"'"

[actions.source]
description = "Open source"
command = "nix-search-tv source --indexes niri '{}' | xargs xdg-open"

[actions.searchgithub]
description = "search github for snippets"
command = "echo 'https://github.com/search?type=code&q=lang:nix+{}' | xargs xdg-open"
mode = "execute"

[ui.status_bar]
hidden = false
