[metadata]
description = "Search nix packages"
name = "nixpkgs"

[preview]
command = "nix-search-tv preview --indexes nixpkgs '{}'"

[source]
command = "nix-search-tv print --indexes nixpkgs"

[keybindings]
ctrl-h = "actions:homepage"
ctrl-s = "actions:source"
ctrl-g = "actions:searchgithub"
enter = "actions:nixshell"

[actions.homepage]
description = "Open homepage"
command = "nix-search-tv homepage --indexes nixpkgs '{}' | xargs xdg-open"

[actions.source]
description = "Open source"
command = "nix-search-tv source --indexes nixpkgs '{}' | xargs xdg-open"

[actions.searchgithub]
description = "search github for snippets"
command = "echo 'https://github.com/search?type=code&q=lang:nix+{}' | xargs xdg-open"

[actions.nixshell]
description = "View files with less"
command = "nix shell nixpkgs#{}"
mode = "execute"

[ui.status_bar]
hidden = false
