[metadata]
description = "Search nur option"
name = "nur"

[preview]
command = "nix-search-tv preview --indexes nur '{}'"

[source]
command = "nix-search-tv print --indexes nur"

[keybindings]
ctrl-h = "actions:homepage"
ctrl-s = "actions:source"
ctrl-g = "actions:searchgithub"
enter = "actions:source"

[actions.homepage]
description = "Open homepage"
command = "nix-search-tv homepage --indexes nur '{}' | xargs -I {} bash -c '[[ \"{}\" != *\"https\" ]] && xdg-open \"{}\"'"

[actions.source]
description = "Open source"
command = "nix-search-tv source --indexes nur '{}' | xargs xdg-open"

[actions.searchgithub]
description = "search github for snippets"
command = "echo 'https://github.com/search?type=code&q=lang:nix+{}' | xargs xdg-open"

[ui.status_bar]
hidden = false
