# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "vmd" "ahci" "nvme" "usb_storage" "usbhid" "uas" "sd_mod" "rtsx_usb_sdmmc" "thunderbolt"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/972c07d3-5181-4de0-bb2d-aaa7d0c6741d";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/972c07d3-5181-4de0-bb2d-aaa7d0c6741d";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/972c07d3-5181-4de0-bb2d-aaa7d0c6741d";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/opt" = {
    device = "/dev/disk/by-uuid/972c07d3-5181-4de0-bb2d-aaa7d0c6741d";
    fsType = "btrfs";
    options = ["subvol=opt"];
  };

  fileSystems."/var/www" = {
    device = "/dev/disk/by-uuid/972c07d3-5181-4de0-bb2d-aaa7d0c6741d";
    fsType = "btrfs";
    options = ["subvol=var/www"];
  };

  fileSystems."/var/spool" = {
    device = "/dev/disk/by-uuid/972c07d3-5181-4de0-bb2d-aaa7d0c6741d";
    fsType = "btrfs";
    options = ["subvol=var/spool"];
  };

  fileSystems."/var/tmp" = {
    device = "/dev/disk/by-uuid/972c07d3-5181-4de0-bb2d-aaa7d0c6741d";
    fsType = "btrfs";
    options = ["subvol=var/tmp"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/972c07d3-5181-4de0-bb2d-aaa7d0c6741d";
    fsType = "btrfs";
    options = ["subvol=var/log"];
  };

  fileSystems."/var/crash" = {
    device = "/dev/disk/by-uuid/972c07d3-5181-4de0-bb2d-aaa7d0c6741d";
    fsType = "btrfs";
    options = ["subvol=var/crash"];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/972c07d3-5181-4de0-bb2d-aaa7d0c6741d";
    fsType = "btrfs";
    options = ["subvol=var/cache"];
  };

  fileSystems."/var/lib/gdm" = {
    device = "/dev/disk/by-uuid/972c07d3-5181-4de0-bb2d-aaa7d0c6741d";
    fsType = "btrfs";
    options = ["subvol=var/lib/gdm"];
  };

  fileSystems."/var/lib/AccountsService" = {
    device = "/dev/disk/by-uuid/972c07d3-5181-4de0-bb2d-aaa7d0c6741d";
    fsType = "btrfs";
    options = ["subvol=var/lib/AccountsService"];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/BDBF-3C87";
    fsType = "vfat";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
