;;; +init.el -*- lexical-binding: t; -*-
(load! "+keymaps.el")
(load! "+org.el")
(load! "+ui.el")
(load! "+dired.el")
(load! "+completion.el")
(load! "+minibuffer.el")
(load! "+treesit.el")
(load! "+treesit-lang.el")
(load! "+eglot.el")
(load! "+tools.el")
