;;; +init.el -*- lexical-binding: t; -*-
(load! "+keymaps.el")
(load! "+org.el")
(load! "+dired.el")
(load! "+completion.el")
(load! "+minibuffer.el")
(load! "+treesit.el")
(load! "+treesit-lang.el")
(load! "+eglot.el")
(load! "+extra.el")
;; (load! "+tools.el")
                                        ; (load! "+clipboard.el")
