;;; +init.el -*- lexical-binding: t; -*-
(load! "+keymaps.el")

(load! "+org.el")
(load! "+org-agenda.el")
(load! "+org-modern.el")
(load! "+org-capture.el")
(load! "+org-capture-doct.el")
(load! "+org-capture-prettify.el")
(load! "+org-roam.el")
(load! "+org-roam-capture.el")
(load! "+visual-fill-column.el")
(load! "+writeroom-mode.el")

(load! "+dired.el")
(load! "+completion.el")
(load! "+minibuffer.el")
(load! "+treesit.el")
(load! "+treesit-lang.el")
(load! "+eglot.el")
(load! "+spell.el")
(load! "+extra.el")
(load! "+org-project-capture.el")
;; (load! "+tools.el")
                                        ; (load! "+clipboard.el")
