[metadata]
description = "Search home-manager option"
name = "home-manager"

[preview]
command = "nix-search-tv preview --indexes home-manager '{}'"

[source]
command = "nix-search-tv print --indexes home-manager"

[keybindings]
ctrl-h = "actions:homepage"
ctrl-s = "actions:source"
ctrl-g = "actions:searchgithub"

[actions.homepage]
description = "Open homepage"
command = "nix-search-tv homepage --indexes home-manager '{}' | xargs -I {} bash -c '[[ \"{}\" != *\"https\" ]] && xdg-open \"{}\"'"

[actions.source]
description = "Open source"
command = "nix-search-tv source --indexes home-manager '{}' | xargs xdg-open"

[actions.searchgithub]
description = "search github for snippets"
command = "echo 'https://github.com/search?type=code&q=lang:nix+{}' | xargs xdg-open"

[ui.status_bar]
hidden = false
