---
name: Update flake

"on":
  push:
  pull_request:
  schedule:
    # 06:00AM PHT everyday except Mon and Fri
    - cron: 0 22 * * 1,2,3,5,6
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: determinatesystems/nix-installer-action@main
      - uses: determinatesystems/magic-nix-cache-action@main
      - uses: determinatesystems/flake-checker-action@main

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update flake inputs
        run: |
          nix flake update --accept-flake-config
          git commit -m "Updated flake inputs" flake.lock || true

      - name: Push commit with updated inputs
        run: |
          git pull --rebase --autostash origin main
          git push origin main
