# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

callPackage ./make-brave-nightly.nix (removeAttrs args [ "callPackage" ]) (
  if stdenv.isAarch64 then
    {
      pname = "brave-browser-nightly";
      version = "1.76.5";
      url = "https://github.com/brave/brave-browser/releases/download/v1.76.5/brave-browser-nightly_1.76.5_arm64.deb";
      hash = "sha256-2vAdF0pn3rRLHNhUVdyjR71OUrdJodN339dc+BNM1Do=";
      platform = "aarch64-linux";
    }
  else if stdenv.isx86_64 then
    {
      pname = "brave-browser-nightly";
      version = "1.76.5";
      url = "https://github.com/brave/brave-browser/releases/download/v1.76.5/brave-browser-nightly_1.76.5_amd64.deb";
      hash = "sha256-NvNlFRjwMbRKUeeCazmzdSbOnBNK59o1UjNQaN1zE0M=";
      platform = "x86_64-linux";
    }
  else
    throw "Unsupported platform."
)
